[workspace]
authors = ["pedestrianlove <jsli@linux.com>"]
channels = ["conda-forge"]
name = "nnUNet"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"

[pypi-dependencies]
torch = { version = ">=2.8.0, <3", index = "https://download.pytorch.org/whl/cu128"}
torchvision = { version = ">=0.23.0, <0.24", index = "https://download.pytorch.org/whl/cu128"}
